In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelEncoder
import pickle

In [2]:
data = pd.read_csv("Churn_Modelling.csv")

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data = data.drop(['RowNumber','CustomerId','Surname'], axis = 1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
labelencoder_gender = LabelEncoder()
data['Gender']=labelencoder_gender.fit_transform(data['Gender'])
data.tail()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
from sklearn.preprocessing import OneHotEncoder

In [7]:
onehotencode_geo  = OneHotEncoder()
geo_encoder = onehotencode_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [8]:
onehotencode_geo.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
geo_encode_df = pd.DataFrame(geo_encoder.toarray(),columns = onehotencode_geo.get_feature_names_out(["Geography"]))
geo_encode_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
# combine one hot encode data with original data
data = pd.concat([data.drop('Geography',axis=1), geo_encode_df],axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [11]:
# save the encoders & scaler
with open('label_encoder_gender.pkl','wb') as files:
    pickle.dump(labelencoder_gender,files)
with open('onehot_encoder_geo.pkl','wb') as files:
    pickle.dump(onehotencode_geo,files)

In [12]:
## divide the dataset dependent into independent features
X=data.drop('Exited',axis=1)
y=data['Exited']

##split the data into training & testing sets
X_train, X_test, y_train,y_test, =train_test_split(X,y,test_size=0.2, random_state=42)

##scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test=  scaler.transform(X_test)

In [13]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [14]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(2000, 12))

In [15]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [16]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [17]:
model = Sequential([
   Dense(64,activation='relu', input_shape=(X_train.shape[1],)), ##H1 connected to  inpt layers
   Dense(32,activation='relu'), ##HL2
   Dense(1,activation='sigmoid')




])

d:\Customer_churn_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
opt= tf.keras.optimizers.Adam(learning_rate=0.01)

In [20]:
##compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [21]:
##set up the tensorBoard
log_dr = "log/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%m%S")
tensorflow_callback = TensorBoard(log_dr,histogram_freq=1)

In [22]:
## set up Earlystopping
early_stopping_callback  = EarlyStopping(monitor='val_loss', patience=10,restore_best_weights=True)

In [23]:
pip install TensorBoard

Requirement already satisfied: TensorBoard in .\venv\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=0.4 in .\venv\Lib\site-packages (from TensorBoard) (2.4.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in .\venv\Lib\site-packages (from TensorBoard) (1.81.1)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from TensorBoard) (3.10.2)
Requirement already satisfied: numpy>=1.12.0 in .\venv\Lib\site-packages (from TensorBoard) (2.5.0)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from TensorBoard) (26.0)
Requirement already satisfied: pillow in .\venv\Lib\site-packages (from TensorBoard) (12.3.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in .\venv\Lib\site-packages (from TensorBoard) (7.35.1)
Requirement already satisfied: setuptools>=41.0.0 in .\venv\Lib\site-packages (from TensorBoard) (82.0.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from TensorBoard) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from TensorBoard) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in .\venv\Lib\site-packages (from grpcio<2.0,>=1.74.0->TensorBoard) (4.16.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->TensorBoard) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [24]:
##train the model
history =model.fit(
    X_train,y_train, validation_data=(X_test,y_test), epochs = 100,
    callbacks=[tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 9s 15ms/step - accuracy: 0.8305 - loss: 0.4051 - val_accuracy: 0.8550 - val_loss: 0.3574
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.8509 - loss: 0.3540 - val_accuracy: 0.8610 - val_loss: 0.3527
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.8565 - loss: 0.3476 - val_accuracy: 0.8600 - val_loss: 0.3440
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8574 - loss: 0.3439 - val_accuracy: 0.8590 - val_loss: 0.3431
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.8595 - loss: 0.3379 - val_accuracy: 0.8580 - val_loss: 0.3446
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8608 - loss: 0.3361 - val_accuracy: 0.8630 - val_loss: 0.3502
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8601 - loss: 0.3349 - val_accuracy: 0.8560 - val_loss: 0.3384
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8627 - loss: 0.3325 - val_accuracy: 0.8655 - val_loss: 0.3446
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - accuracy: 0.8596 - loss: 0.3338 - val_accuracy: 0.8575 - val_loss: 0.3394
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 15ms/step - accuracy: 0.8639 - loss: 0.3303 - val_accuracy: 0.8625 - val_loss: 0.3411
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - accuracy: 0.8624 - loss: 0.3308 - val_accuracy: 0.8640 - val_loss: 0.3380
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.8636 - loss: 0.3265 - val_accuracy: 0.8620 - val_loss: 0.3477
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - accuracy: 0.8660 - loss: 0.3245 - val_accuracy: 0.8600 - val_loss: 0.3443
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.8655 - loss: 0.3245 - val_accuracy: 0.8580 - val_loss: 0.3413
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 18ms/step - accuracy: 0.8634 - loss: 0.3240 - val_accuracy: 0.8600 - val_loss: 0.3548
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8658 - loss: 0.3201 - val_accuracy: 0.8510 - val_loss: 0.3541
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.8669 - loss: 0.3165 - val_accuracy: 0.8505 - val_loss: 0.3522
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8679 - loss: 0.3173 - val_accuracy: 0.8590 - val_loss: 0.3427
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8683 - loss: 0.3112 - val_accuracy: 0.8620 - val_loss: 0.3646
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8714 - loss: 0.3111 - val_accuracy: 0.8535 - val_loss: 0.3528
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 6s 13ms/step - accuracy: 0.8692 - loss: 0.3083 - val_accuracy: 0.8615 - val_loss: 0.3674

In [25]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [26]:
%load_ext tensorboard

In [28]:
pip install tensorflow

Requirement already satisfied: tensorflow in .\venv\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in .\venv\Lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in .\venv\Lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in .\venv\Lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in .\venv\Lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in .\venv\Lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in .\venv\Lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in .\venv\Lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in .\venv\Lib\site-packages (from tensorflow) (7.35.1)
Requirement already satisfied: requests<3,>=2.21.0 in .\venv\Lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in .\venv\Lib\site-packages (from tensorflow) (82.0.1)
Requirement already satisfied: six>=1.12.0 in .\venv\Lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in .\venv\Lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in .\venv\Lib\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in .\venv\Lib\site-packages (from tensorflow) (2.2.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in .\venv\Lib\site-packages (from tensorflow) (1.81.1)
Requirement already satisfied: keras>=3.12.0 in .\venv\Lib\site-packages (from tensorflow) (3.15.0)
Requirement already satisfied: numpy>=1.26.0 in .\venv\Lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in .\venv\Lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in .\venv\Lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Requirement already satisfied: wheel<1.0,>=0.23.0 in .\venv\Lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in .\venv\Lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in .\venv\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in .\venv\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\venv\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\venv\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in .\venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [27]:
%tensorboard --logdir log/fit

Reusing TensorBoard on port 6007 (pid 10652), started 1 day, 19:11:52 ago. (Use '!kill 10652' to kill it.)